config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get 'settings', to: 'users#settings'
  get 'home', to: 'home#index'
  get 'delete_user', to: 'users#delete_user'

  post 'login', to: 'sessions#create'
  post 'close_days', to: 'close_days#data'
  post 'save_setting_detail', to: 'close_days#setting_detail'
  post 'save_other_close_days', to: 'close_days#other_close_days'

  delete 'logout', to: 'sessions#destroy'

  resources :users, only: %i[new create]
  
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  account_delete  :boolean          default(FALSE), not null
#  admin_authority :boolean          default(FALSE), not null
#  mail            :string(255)      not null
#  name            :string(255)      not null
#  password_digest :string(255)      not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
# Indexes
#
#  index_users_on_name_and_mail  (name,mail) UNIQUE
#
class User < ApplicationRecord
  has_many :settings, dependent: :destroy
  has_many :DaiNumberCloseDay, dependent: :destroy

  has_secure_password
  
  validates :name,
    presence: true,
    uniqueness: true,
    length: { maximum: 16 },
    format: {
      with: /\A[a-z0-9]+\z/,
      message: 'は小文字英数字で入力してください'
    }
  validates :password,
    length: { minimum: 8 }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include Common
  require "json"
  require 'fileutils'
  require 'date_helper'

  def new
    @user = User.new(flash[:user])
    unless @current_user
      render :layout => 'users/application'
      return
    end
    redirect_to settings_path
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      session[:user_name] = user.name
      Setting.create(user_id: user.id)

      o = [('0'..'9'),('a'..'z'), ('A'..'Z')].map(&:to_a).flatten
      string = (0...25).map { o[rand(o.length)] }.join
      tag_name = "#{string}_#{user.id}"
      setting = Setting.find_by(user_id: user.id)
      setting.tag_name = tag_name
      setting.save
      save_js_tag(user.id, tag_name)

      redirect_to settings_path
    else
      redirect_back fallback_location: new_user_path, flash: {
        user: user,
        error_messages: user.errors.full_messages
      }
    end  
  end

  def week_day_numbers
    [0, 1, 2, 3, 4, 5, 6]
  end

  def week_day_names
    ['日', '月', '火', '水', '木', '金', '土']
  end

  def settings
    account_id = session[:user_id]
    @dai_week_name = ["第-1", "第-2", "第-3", "第-4"]
    
    # 設定データ
    @setting = Setting.find_by(user_id: account_id)
    @setting_weekly_days = @setting.weekly_days.blank? ? [] : @setting.weekly_days.split(',').map(&:to_i)
    
    # 定休日の日を取得
    @this_month_weekly_close_days = dates_of_weekly(@setting_weekly_days, Date.today.beginning_of_month)
    @next_month_weekly_close_days = dates_of_weekly(@setting_weekly_days, Date.today.beginning_of_month.next_month)
  
    # 定休日以外
    @others_close_days = @setting.others_close_days
    @next_month_others_close_days = @setting.next_month_others_close_days

    # 第休取得
    @this_month_dai_number_close_day, @next_month_dai_number_close_day = date_of_dai_close_day(account_id)

  end

  def get_dai_data(dai_week_number)
    dai_number_close_day = DaiNumberCloseDay.find_by(user_id: session[:user_id], dai_week_number: dai_week_number)
    dai_number_close_day ? dai_number_close_day['dai_close_day_number'].split(',').map(&:to_i) : []
  end

  def tag_url
    account_id = session[:user_id]
    setting = Setting.find_by(user_id: account_id)
    subdomain = request.subdomain.present? ? "#{request.subdomain}." : ""
    tag_url = '<script type="text/javascript" src="' + request.protocol + subdomain + request.domain + '/tag/' + setting.tag_name.to_s + '.js"></script>'
  end

  def delete_user
    user_id = params[:id].to_i
    user = User.find_by(id: user_id)
    setting = Setting.find_by(user_id: user_id)
    dai_number = DaiNumberCloseDay.find_by(user_id: user_id)

    user.destroy if  user.present?
  end

  helper_method :week_day_numbers, :week_day_names, :get_dai_data, :tag_url

  private

  def user_params
    params.require(:user).permit(:name, :mail, :password, :password_confirmation)
  end

  def save_js_tag(account_id, tag_name)
    path = "#{Rails.public_path}/tag/#{tag_name}.js"
    subdomain = request.subdomain.present? ? "#{request.subdomain}." : ""
    tag = %[
      $.when(
        close_days_script = document.createElement('script'),
        close_days_script.type = 'text/javascript',
        close_days_script.src = "#{request.protocol}#{subdomain}#{request.domain}/js/close_days.js?" + Date.now(),
        close_days_script.charset = 'UTF-8',
        document.getElementsByTagName('body')[0].appendChild(close_days_script),
        close_days_css = '<link rel="stylesheet" rel="nofollow" href="#{request.protocol}#{subdomain}#{request.domain}/css/close_days.css?' + Date.now() + '" type="text/css">',
        $('head').append(close_days_css)
      ).done(function () {
        $(document).ready(function () {
          url = "#{request.protocol}#{subdomain}#{request.domain}/close_days";
          let close_days_fun_count = 0;
          let close_days_interval = setInterval(function () {
            if (typeof show_close_days_calendar == 'function') {
              show_close_days_calendar(#{account_id}, url);
              clearInterval(close_days_interval);
            }
            if (++close_days_fun_count > 1000) {
              clearInterval(close_days_interval);
            }
          }, 100);
        });
      });
          ]
    
    File.open(path, "w+") do |f|
      f.write(tag)
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<section class="signup">
  <div class="authentication_container">
    <div class="signup-content">
      <div class="signup-form">
          <h2 class="form-title">アカウント登録</h2>
          <%= form_with model: user do |f| %>
            <div class="form-group">
              <%= f.label :name, 'name' do %>
                <i class="zmdi zmdi-account material-icons-name"></i>
              <% end %>
              <%= f.text_field :name, class: '', placeholder: '名前' %>
            </div>
            <div class="form-group">
              <%= f.label :mail, 'mail' do %>
                <i class="zmdi zmdi-email"></i>
              <% end %>
              <%= f.text_field :mail, class: '', placeholder: 'メールアドレス' %>
            </div>
            <div class="form-group">
              <%= f.label :password, 'password' do %>
                <i class="zmdi zmdi-key"></i>
              <% end %>
              <%= f.password_field :password, class: '', placeholder: 'パスワード' %>
            </div>
            <div class="form-group">
              <%= f.label :password_confirmation, 'password' do %>
                <i class="zmdi zmdi-key"></i>
              <% end %>
              <%= f.password_field :password_confirmation, class: '', placeholder: 'パスワード（確認）' %>
            </div>
            <div class="form-group form-button">
              <%= f.submit '登録', class: 'form-submit' %>
            </div>
          <% end %>
        </div>
      <div class="signup-image">
        <figure>
          <img src="<%= asset_path('signup-image.jpg') %>" alt="sing up image">
        </figure>
        <%= link_to 'ログインページへ', home_path, class: 'signup-image-link' %>
      </div>
    </div>
  </div>
</section>

app/views/users/_login_form.html.erb
<section class="signup">
  <div class="authentication_container">
    <div class="signup-content">
      <div class="signup-form">
          <h2 class="form-title">ログイン</h2>
          <%= form_with scope: :session, url: login_path do |f| %>
            <div class="form-group">
              <%= f.label :name, 'name' do %>
                <i class="zmdi zmdi-account material-icons-name"></i>
              <% end %>
              <%= f.text_field :name, class: '', placeholder: '名前' %>
            </div>
            <div class="form-group">
              <%= f.label :password, 'password' do %>
                <i class="zmdi zmdi-email"></i>
              <% end %>
              <%= f.password_field :password, class: '', placeholder: 'パスワード' %>
            </div>
            <div class="form-group form-button">
              <%= f.submit 'ログイン', class: 'form-submit' %>
            </div>
          <% end %>
        </div>
      <div class="signup-image">
        <figure>
          <img src="<%= asset_path('signup-image.jpg') %>" alt="sing up image">
        </figure>
      </div>
    </div>
  </div>
</section>

app/views/users/delete_user.html.erb
削除

app/views/users/me.html.erb
<h1>Users#me</h1>
<p>Find me in app/views/users/me.html.erb</p>

app/views/users/new.html.erb
<%= render partial: 'form', locals: { user: @user } %>

app/views/users/settings.html.erb
<div class="card">
  <div class="card-header">
    タグ
  </div>
  <div class="card-body">
    <%= tag_url %>
  </div>
</div>
<br>

<div class="card">
  <div class="card-header">
    詳細設定
  </div>
  <div class="card-body weekly_setting">
    <div class="row">
      <div class="col-3">
        <p class="text-end weekly_text text-danger">公開する：</p>
      </div>
      <div class="col-8">
        <div class="">
          <div class="form-check form-check-inline">
            <input class="form-check-input" type="checkbox" id="publish" value="1" <%= 'checked' if @setting.publish %>>
          </div>
        </div>
      </div>
    </div>
    <hr>
    <div class="row">
      <div class="col-3">
        <p class="text-end weekly_text">毎週定休日：</p>
      </div>
      <div class="col-8">
        <div class="mb-3">
          <% week_day_numbers.each do |number| %>
            <div class="form-check form-check-inline">
              <input class="form-check-input week_day_numbers" type="checkbox" id="week_day_<%= number %>" value="<%= number %>" <%= 'checked' if @setting_weekly_days.include?(number) %>>
              <label class="form-check-label" for="week_day_<%= number %>"><%= week_day_names[number] %></label>
            </div>
          <% end %>
        </div>
      </div>
    </div>

    <%# 第 %>
    <input type="hidden" id="this_month_dai_number_close_day" value="<%= @this_month_dai_number_close_day.join(',') %>">
    <input type="hidden" id="next_month_dai_number_close_day" value="<%= @next_month_dai_number_close_day.join(',') %>">
    <% @dai_week_name.each_with_index do |name, index|%>
    <% num = index + 1 %>
    <% arr = get_dai_data(num) %>
      <div class="row">
        <div class="col-3">
          <p class="text-end weekly_text"><%= name %>の休日：</p>
        </div>
        <div class="col-8">
          <div class="mb-3 dai_<%= num %>">
            <% week_day_numbers.each do |number| %>
              <div class="form-check form-check-inline">
                <input class="form-check-input dai_day_numbers" type="checkbox" id="dai_day_<%= number %>" value="<%= number %>" <%= 'checked' if arr.include?(number) %>>
                <label class="form-check-label" for="dai_day_<%= number %>"><%= week_day_names[number] %></label>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
    <hr>
    <div class="row">
      <div class="col-3">
        <p class="text-end weekly_text">id値である：</p>
      </div>
      <div class="col-8">
        <div class="mb-3">
          <div class="form-check form-check-inline">
            <input class="form-check-input" type="checkbox" id="element_id_flag" value="1" checked disabled>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-3">
        <p class="text-end weekly_text">表示要素名：</p>
      </div>
      <div class="col-8">
        <div class="input-group input-group-sm mb-3">
          <div class="col-sm-4">
            <input value="<%= @setting.element_name %>" type="text" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-sm" id="element_name">
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-3">
        <p class="text-end weekly_text">背景：</p>
      </div>
      <div class="col-8">
        <div class="input-group input-group-sm mb-3">
          <div class="col-sm-4">
            <input type="color" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-sm" id="background_color" value="<%= @setting.background_color.blank? ? '#CC0000' : @setting.background_color %>">
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-3">
        <p class="text-end weekly_text">文字色：</p>
      </div>
      <div class="col-8">
        <div class="input-group input-group-sm mb-3">
          <div class="col-sm-4">
            <input type="color" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-sm" id="font_color" value="<%= @setting.font_color.blank? ? '#ffffff' : @setting.font_color %>">
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-3">
        <p class="text-end weekly_text">タイトル：</p>
      </div>
      <div class="col-8">
        <div class="input-group input-group-sm mb-3">
          <div class="col-sm-10">
            <input type="text" value="<%= @setting.title %>" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-sm" id="title">
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-3">
      </div>
      <div class="col-8">
        <div class="mb-3">
          <div id="save_weekly_data" class="btn btn-primary weekly_close_days">保存</div>
        </div>
      </div>
    </div>
  </div>
</div>

<br>
<br>

<div class="card">
  <div class="card-header">
    定休日以外設定
  </div>
  <div class="card-body">
    <div class="wrapper">
      <div class="this_month">
        <input type="hidden" id="this_month_weekly_close_days" value="<%= @this_month_weekly_close_days.join(",") %>">
        <input type="hidden" id="others_close_days" value="<%= @others_close_days %>">
        <!-- xxxx年xx月を表示 -->
        <h1 id="header"></h1>
        <!-- カレンダー -->
        <div id="calendar"></div>
      </div>
      <div class="next_month">
        <input type="hidden" id="next_month_weekly_close_days" value="<%= @next_month_weekly_close_days.join(",") %>">
        <input type="hidden" id="next_month_others_close_days" value="<%= @next_month_others_close_days %>">
        <!-- xxxx年xx月を表示 -->
        <h1 id="header"></h1>
        <!-- カレンダー -->
        <div id="calendar"></div>
      </div>
    </div>
    <div class="row mt-5">
      <div class="col-12 text-center">
        <div id="save_other_close_days" class="btn btn-primary weekly_close_days">保存</div>
      </div>
    </div>
  </div>
</div>