config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get 'settings', to: 'users#settings'
  get 'home', to: 'home#index'
  get 'delete_user', to: 'users#delete_user'

  post 'login', to: 'sessions#create'
  post 'close_days', to: 'close_days#data'
  post 'save_setting_detail', to: 'close_days#setting_detail'
  post 'save_other_close_days', to: 'close_days#other_close_days'

  delete 'logout', to: 'sessions#destroy'

  resources :users, only: %i[new create]
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :current_user

  private

  def current_user
    return unless session[:user_id]
    @current_user = User.find_by(id: session[:user_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def header_link_item(name, path)
    class_name = 'nav-item'
    class_name << ' active' if current_page?(path)

    content_tag :li, class: class_name do
      link_to name, path, class: 'nav-link'
    end
  end
end

app/views/application/_application_head.html.erb
<head>
    <title>show business days</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="../fonts/material-icon/css/material-design-iconic-font.min.css">
    <%= favicon_link_tag('/favicon.png') %>
</head>

app/views/application/_header_navi.html.erb
<nav class="navbar">
  <div class="navi_container">
    <div class="navi_container_logo">
      <i class="zmdi zmdi-home material-icons-name"></i>
      <%= link_to 'ホーム', root_path, class: '' %>
    </div>
    <ul class="nav nav-right">
      <% if @current_user %>
          <li>
            <i class="zmdi zmdi-account material-icons-name"></i>
            <span class="text-white"><%= session[:user_name] %>様</span>
          </li>
          <li>
            <i class="zmdi zmdi-settings material-icons-name"></i>
            <%= link_to '設定ページ', settings_path, class: '' %>
          </li>
          <li>
            <i class="zmdi zmdi-square-right material-icons-name"></i>
            <%= link_to 'ログアウト', logout_path, method: :delete, class: 'n' %>
          </li>
      <% else %>
          <li><%= link_to 'アカウント登録', new_user_path, class: '' %></li>
          <li><%= link_to 'ログイン', root_path, class: '' %></li>
      <% end %>
    </ul>
  </div><!--/.navi_container-->
</nav><!--/.navbar-->